import type { Metadata } from 'next';
// import { Fugaz_One } from 'next/font/local';
import { Fugaz_One } from 'next/font/google';
import './globals.css';

const Fugaz = Fugaz_One({ subsets: ['latin'], weight: ['400'] });
export const metadata: Metadata = {
  title: 'moodmoji',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const header = (
    <header className='p-4 sm:p-8 flex items-center justify-between gap-4'>
      <h1 className={`text-base sm:text-lg ` + Fugaz.className}>moodmoji</h1>
    </header>
  );
  const footer = <footer>foot</footer>;
  return (
    <html lang='en'>
      <body
        className={`w-full max-w[1000px] mx-auto text-sm sm:text-base min-h-screen flex flex-col `}
      >
        {header}
        {children}
        {footer}
      </body>
    </html>
  );
}
